set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR "x86_64")

set(CMAKE_C_COMPILER   "/usr/bin/x86_64-w64-mingw32ucrt-gcc")
set(CMAKE_CXX_COMPILER "/usr/bin/x86_64-w64-mingw32ucrt-g++")
set(CMAKE_RC_COMPILER  "/usr/bin/x86_64-w64-mingw32ucrt-windres")

set(CMAKE_FIND_ROOT_PATH "/usr/x86_64-w64-mingw32ucrt/sys-root/mingw/")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING_EMULATOR "/usr/bin/wine64")
